fun main() {
    println("Enter the following: ")
    print("Enrollment Number : ")
    val en = readLine()
    print("Student Name : ")
    val name = readLine()
    print("Student Branch : ")
    val sb = readLine()
    print("Student Class : ")
    val sc = readLine()
    print("Student Batch : ")
    val sba = readLine()
    print("Student College Name : ")
    val scn = readLine()
    print("Student University Name : ")
    val sun = readLine()
    print("Student Age : ")
    val age = readLine()
    println("************************")
    println("Student's Information")
    println("Enrollment No : $en")
    println("Name : $name")
    println("Age : $age")
    println("Branch : $sb")
    println("Class : $sc")
    println("Batch : $sba")
    println("College Name : $scn")
    println("University Name : $sun")
}
